###Python Pandas working with XML 
1. Read XML and get Dataframe
2. convert Dataframe to xml

In [1]:
import pandas as pd

In [16]:
xml = '''<?xml version='1.0' encoding='utf-8'?>
<data xmlns="http://example.com">
 <row>
   <shape>square</shape>
   <degrees>360</degrees>
   <sides>4.0</sides>
   <firstname>Sagar</firstname>
 </row>
 <row>
   <shape>circle</shape>
   <degrees>360</degrees>
   <sides/>
   <firstname/>
 </row>
 <row>
   <shape>triangle</shape>
   <degrees>180</degrees>
   <sides>3.0</sides>
   <firstname/>
 </row>
</data>'''

In [17]:
pd.read_xml(xml)

      shape  degrees  sides firstname
0    square      360    4.0     Sagar
1    circle      360    NaN      None
2  triangle      180    3.0      None

In [23]:
xml = '''<?xml version='1.0' encoding='utf-8'?>
<data>
  <row shape="square" degrees="360" sides="4.0" firstname="Sagar"/>
  <row shape="circle" degrees="360" sides="5.0" middlename="B"/>
  <row shape="triangle" degrees="180" sides="3.0" lastname="Pandya"/>
</data>'''

In [24]:
pd.read_xml(xml)

      shape  degrees  sides firstname middlename lastname
0    square      360    4.0     Sagar       None     None
1    circle      360    5.0      None          B     None
2  triangle      180    3.0      None       None   Pandya

In [25]:
pd.read_xml(xml,xpath=".//row")

      shape  degrees  sides firstname middlename lastname
0    square      360    4.0     Sagar       None     None
1    circle      360    5.0      None          B     None
2  triangle      180    3.0      None       None   Pandya

In [26]:
xml = '''<?xml version='1.0' encoding='utf-8'?>
<doc:data xmlns:doc="https://example.com">
  <doc:row>
    <doc:shape>square</doc:shape>
    <doc:degrees>360</doc:degrees>
    <doc:sides>4.0</doc:sides>
  </doc:row>
  <doc:row>
    <doc:shape>circle</doc:shape>
    <doc:degrees>360</doc:degrees>
    <doc:sides/>
  </doc:row>
  <doc:row>
    <doc:shape>triangle</doc:shape>
    <doc:degrees>180</doc:degrees>
    <doc:sides>3.0</doc:sides>
  </doc:row>
</doc:data>'''

In [27]:
df=pd.read_xml(xml,xpath=".//doc:row",namespaces={"doc": "https://example.com"})

In [28]:
df.to_xml('test1.xml')

In [30]:
df

      shape  degrees  sides
0    square      360    4.0
1    circle      360    NaN
2  triangle      180    3.0